// SPDX-License-Identifier: Apache-2.0
#define IREE_PLATFORM_GENERIC 1
#define IREE_FILE_IO_ENABLE 0
#define IREE_TIME_NOW_FN { return 0; }
#define IREE_WAIT_UNTIL_FN(ns) ((void)(ns), false)
#define IREE_SYNCHRONIZATION_DISABLE_UNSAFE 1
#define IREE_STATUS_FEATURES 3
#define IREE_STATISTICS_ENABLE 0
#define IREE_HAL_STATISTICS_ENABLE 0
