set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER "$ENV{LLVM_INSTALL_DIR}/bin/clang")
set(CMAKE_CXX_COMPILER "$ENV{LLVM_INSTALL_DIR}/bin/clang++")
set(CMAKE_ASM_COMPILER "$ENV{LLVM_INSTALL_DIR}/bin/clang")
set(CMAKE_AR "$ENV{LAB_TOOLS}/llvm/bin/llvm-ar")
set(CMAKE_RANLIB "$ENV{LAB_TOOLS}/llvm/bin/llvm-ranlib")
set(_flags "-march=rv64gc -mabi=lp64d -mcmodel=medany -mno-relax -fno-vectorize -fno-slp-vectorize -ffp-contract=off -ffunction-sections -fdata-sections -isystem $ENV{ARA_GCC_ROOT}/riscv-none-elf/include -include ${CMAKE_CURRENT_LIST_DIR}/../runtime/iree_config.h")
set(CMAKE_C_FLAGS "${_flags}" CACHE STRING "Pinned Proton runtime flags" FORCE)
set(CMAKE_CXX_FLAGS "${_flags}" CACHE STRING "Pinned Proton runtime flags" FORCE)
set(CMAKE_ASM_FLAGS_INIT "-march=rv64gcv_zfh_zvfh -mabi=lp64d -mcmodel=medany -mno-relax")
if(PROTON_DDR)
  set(_linker link-ddr.ld)
else()
  set(_linker link.ld)
endif()
set(CMAKE_EXE_LINKER_FLAGS_INIT "-nostartfiles -static -Wl,--gc-sections -T${CMAKE_CURRENT_LIST_DIR}/../runtime/proton/${_linker}")
